### PR TITLE
Add support for some 3DS games

### PR DESCRIPTION
**Pull request by DaniElectra**
This pull request adds compatibility for parsing packets from some 3DS titles. Marked as draft as I'd like to add and test some more games.

### Additions

- Implement the Friends 3DS (partially), only the methods that are called when idling or playing a game
- Implement the Utility protocol
- Implement the Service Item protocol
- Implement the Shop protocol for Pokémon Bank and Badge Arcade
- Add some 3DS games to the title list
- Add patches for existing protocols that are modified on Badge Arcade and Pokémon Bank packets
- Split NEX versions of protocols to individual files

### Tested games

- [X] Mario Kart 7
- [X] Badge Arcade
- [X] Pokémon Bank
- [X] IronFall Invasion
- [X] Steel Diver: Sub Wars
- [X] Team Kirby Clash Deluxe
- [X] Yokai Watch 2: Bony Spirits/Fleshy Souls (only have the latter one, probably use the same access key?)

### Notes

- [X] Protocols that use custom IDs have not been implemented yet
- Patched `build_games_list.js` to ignore the newlines at EOF
- Fixed the `ReportNATTraversalResult` request, which has a parameter that doesn't exist on the 3DS. Check if there's data remaining to read to determine whether to read the parameter or not.
- Some games like IronFall Invasion use Quazal Net-Z for peer to peer connections. Filter those packets by checking the source and destination on PRUDPv1
- The list with NEX versions has been moved to the `nex` folder, to leave the root directory clean. The exact Matchmaking version of Mario Kart 7 is unknown (we know is lower than 3.0), so left as 2.0.0
- Patches on Ranking and Utility have been added for Mario Kart 7, as it implements custom methods but we don't know the contents yet
- Some NEX version checks on parameters have been replaced by structure version checks
- The `extendedProtocolId` value on packets has been renamed to `customId`

### CODE REVIEW

**Comment by jonbarrow** [comment]
I see you're fixing up the title JSON creator. I got the data for the first version from here https://kinnay.github.io/view.html?page=wiiu

If you click the `colums` button a drop down shows where you can select what data is in the table. There is a `NEX` section which has details about specific protocols

NEX = The base NEX client
NEX-DS = DataStore
NEX-MS = Messaging
NEX-RK = Ranking/Ranking 2
NEX-MM = Matchmaking
NEX-UT = Utility

There is also a Quazal version which may be interesting to use too since I plan to support Ubisoft games eventually anyway

**Comment by DaniElectra** [comment]
> I see you're fixing up the title JSON creator. I got the data for the first version from here https://kinnay.github.io/view.html?page=wiiu
> 
> If you click the `colums` button a drop down shows where you can select what data is in the table. There is a `NEX` section which has details about specific protocols
> 
> NEX = The base NEX client NEX-DS = DataStore NEX-MS = Messaging NEX-RK = Ranking/Ranking 2 NEX-MM = Matchmaking NEX-UT = Utility
> 
> There is also a Quazal version which may be interesting to use too since I plan to support Ubisoft games eventually anyway

Thanks for the details! I'll split those protocols and check for version differences.

I can take a look for implementing Quazal support later, but I'll keep this PR focused on the 3DS

**Comment by jonbarrow** [comment]
Sounds good!

**Comment by DaniElectra** [comment]
This PR is ready for review! I might try to decode the unknown methods on MK7, but I think this is fine for now!

**Comment by jonbarrow** [comment]
Absolutely amazing, great work as usual!

**Pull request merged**
